---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: tripviewer
  name: tripviewer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    io.kompose.service: tripviewer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tripviewer
  name: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tripviewer
  template:
    metadata:
      labels:
        io.kompose.network/tripinsights: "true"
        io.kompose.service: tripviewer
    spec:
      containers:
        - name: tripviewer
          image: registrybih8575.azurecr.io/tripviewer:1.0
          env:
            - name: TRIPS_API_ENDPOINT
              value: "http://trips:8081/api/trips"
            - name: USERPROFILE_API_ENDPOINT
              value: "http://userprofile:8083/api/user"
            - name: BING_MAPS_KEY
              value: "DUMMY"
          envFrom:
            - configMapRef: 
                name: sql-connect-cm
            - secretRef:
                name: sql-connect-secrets
          resources:
            limits:
              memory: "1Gi"
              cpu: "250m"
            requests:
              memory: "1Gi"
              cpu: "250m"
      restartPolicy: Always
