---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trips
  name: trips
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
  selector:
    app: trips
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trips
  name: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
        - name: trips
          image: registrybih8575.azurecr.io/trips:1.0
          env:
            # - name: ASPNETCORE_ENVIRONMENT
            #   value: Production
            - name: DOCS_URI
              value: http://temp
          envFrom:
            - configMapRef: 
                name: sql-connect-cm
            - secretRef:
                name: sql-connect-secrets
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "1Gi"
              cpu: "250m"
            requests:
              memory: "1Gi"
              cpu: "250m"
      restartPolicy: Always

