---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: userprofile
  name: userprofile
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 80
  selector:
    io.kompose.service: userprofile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: userprofile
  name: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: userprofile
  template:
    metadata:
      labels:
        io.kompose.network/tripinsights: "true"
        io.kompose.service: userprofile
    spec:
      containers:
        - name: userprofile
          image: registrybih8575.azurecr.io/userprofile:1.0
          envFrom:
            - configMapRef: 
                name: sql-connect-cm
            - secretRef:
                name: sql-connect-secrets
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "1Gi"
              cpu: "250m"
            requests:
              memory: "1Gi"
              cpu: "250m"
      restartPolicy: Always

