---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: user-java
  name: user-java
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 80
  selector:
    io.kompose.service: user-java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: user-java
  name: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-java
  template:
    metadata:
      labels:
        io.kompose.service: user-java
    spec:
      containers:
        - name: user-java
          image: registrybih8575.azurecr.io/user-java:1.0
          envFrom:
            - configMapRef: 
                name: sql-connect-cm
            - secretRef:
                name: sql-connect-secrets
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "1Gi"
              cpu: "250m"
            requests:
              memory: "1Gi"
              cpu: "250m"
      restartPolicy: Always

